apiVersion: v1
kind: Secret
metadata:
  name: olist-secrets
  namespace: olist
type: Opaque
stringData:
  DB_USERNAME: olist_user
  DB_PASSWORD: olist_pass
  KC_DB_USERNAME: keycloak_user
  KC_DB_PASSWORD: keycloak_pass
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_CLIENT_SECRET: olist-client-secret
  VAULT_TOKEN: vault-root-token
