apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-app-pvc
  namespace: olist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-pvc
  namespace: olist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
